apiVersion: v1
kind: Template
metadata:
  name: demotemplate
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: ${APPNAME}
    name: ${APPNAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPNAME}
      deploymentconfig: ${APPNAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
      deployment: ${APPNAME}-1
      deploymentconfig: ${APPNAME}
  spec:
    containers:
    - image: registry.lab.example.com:5000/demo/demoapp
      imagePullPolicy: Always
      name: ${APPNAME}
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPNAME}
    name: ${APPNAME}
  spec:
    host: ${APPNAME}.apps.lab.example.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APPNAME}
      weight: 100
    wildcardPolicy: None
parameters:
  - description: Application Name
    name: APPNAME
    required: true
    generate: expression
    from: "demoapp[0-9a-f]{3}"
    
